config/routes.rb
Rails.application.routes.draw do
  get 'passwords/new'
  get 'passwords/edit'
  
  # Rota para verificar a saúde da aplicação
  get "up" => "rails/health#show", as: :rails_health_check

  # Rotas de login e cadastro
  get 'signup', to: 'users#new', as: 'signup'
  post 'signup', to: 'users#create'

  get 'get_all_users', to: 'users#get_all_users'
  get 'login', to: 'users#login'
  post 'login', to: 'users#create_session', as: 'create_session_users'

  # Rota para redefinir senha
  get 'password/new', to: 'passwords#new', as: :new_password
  post 'password/reset', to: 'passwords#create', as: :reset_password
  get 'password/edit', to: 'passwords#edit', as: :edit_password
  patch 'password/update', to: 'passwords#update', as: :password_update

  # Definição da rota raiz para a tela de login
  root 'users#login'

  # Rota para a tela inicial
  get 'home', to: 'users#home', as: 'home'

  # Rota para sair da conta
  get '/logout', to: 'sessions#destroy'

  # Rotas para emitir relatórios
  get 'emitir_relatorio', to: 'reports#emitir', as: 'emitir_relatorio'
 
  # Definições das rotas para os recursos
  resources :tarefas do
    member do
      patch :marcar_como_concluida
    end
  end
  resources :categorias
  resources :lembretes
  resources :metas do
    member do
      patch :marcar_como_concluida
    end
  end
  resources :users
  resources :planner_views
  resources :statuses

end

app/models/meta.rb
class Meta < ApplicationRecord
    has_one :categoria
    has_one :status

    validates :data_inicio, presence: true
    validates :data_fim, presence: true
    validates :descricao, presence: true
end

app/controllers/metas_controller.rb
class MetasController < ApplicationController
  before_action :set_meta, only: %i[show edit update destroy]

  # GET /metas
  def index
    @metas_por_data = Meta.where.not(status_id: 3).group_by(&:data_inicio)
    
    respond_to do |format|
      format.html
      format.json { render json: @metas_por_data }
    end
  end
  

  # metas_controller.rb
  def marcar_como_concluida
    @meta = Meta.find(params[:id])
    if @meta.update(status_id: 3) # Altera para o ID do status "Concluído"
      render json: { success: true, message: 'Meta concluída com sucesso!' }
    else
      render json: { success: false, message: 'Erro ao concluir a meta.' }
    end
  end
  
  # GET /metas/:id
  def show
  end

  # GET /metas/new
  def new
    @categorias = Categoria.all # Pegue todas as categorias do banco
    @meta = Meta.new
  end

  # GET /metas/:id/edit
  def edit
  end

  # POST /metas
  def create
    @meta = Meta.new(meta_params)

    if @meta.save
      redirect_to home_path, notice: 'Meta foi criada com sucesso.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /metas/:id
  def update
    if @meta.update(meta_params)
      redirect_to @meta, notice: 'Meta foi atualizada com sucesso.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /metas/:id
  def destroy
    @meta.destroy
    redirect_to metas_url, notice: 'Meta foi removida com sucesso.'
  end

  private

  # Use callbacks para compartilhar configurações ou restrições comuns entre as ações.
  def set_meta
    @meta = Meta.find(params[:id])
  end

  # Apenas permita uma lista de parâmetros confiáveis.
  def meta_params
    params.require(:meta).permit(:descricao, :data_inicio, :data_fim, :status_id, :categoria_id)
  end
end

app/helpers/metas_helper.rb
module MetasHelper
end

app/views/metas/new.html.erb
<%= stylesheet_link_tag 'metas', media: 'all' %>
<body class="metas">
<div class="form-container centralizar-metas"> 
  <%= form_with(model: @meta, url: metas_path, local: true) do |form| %>
    
    <h1 class="titulo-metas">Criar Meta</h1>

    <div class="field-group_metas">
      <div class="field_data">
        <%= form.label :data_inicio, "Data Início", class: "label-meta" %>
        <%= form.date_field :data_inicio, class: "input-meta" %>
      </div>

      <div class="field_data">
        <%= form.label :data_fim, "Data Fim", class: "label-meta" %>
        <%= form.date_field :data_fim, class: "input-meta" %>
      </div>
    </div>

    <div class="field">
      <%= form.label :descricao, "Descrição", class: "label-meta" %>
      <%= form.text_area :descricao, rows: 3, class: "input-meta" %>
    </div>

    <div class="field-group_metas">
      <div class="field_total">
        <%= form.label :status_id, "Status", class: "label-meta" %>
        <%= form.collection_select :status_id, Status.all, :id, :nome, { prompt: "Selecione um Status" }, { class: "input-meta" } %>
      </div>

      <div class="field_total">
        <%= form.label :categoria_id, "Categoria", class: "label-meta" %>
        <%= form.collection_select :categoria_id, Categoria.all, :id, :nome, { prompt: "Selecione uma Categoria" }, { class: "input-meta" } %>
      </div>
    </div>

    <div class="metas-actions">
      <%= form.submit "Criar Meta", class: "btn-meta" %>
    </div>
    
  <% end %>
</div>
</body>