config/routes.rb
Rails.application.routes.draw do
  get 'passwords/new'
  get 'passwords/edit'
  
  # Rota para verificar a saúde da aplicação
  get "up" => "rails/health#show", as: :rails_health_check

  # Rotas de login e cadastro
  get 'signup', to: 'users#new', as: 'signup'
  post 'signup', to: 'users#create'

  get 'get_all_users', to: 'users#get_all_users'
  get 'login', to: 'users#login'
  post 'login', to: 'users#create_session', as: 'create_session_users'

  # Rota para redefinir senha
  get 'password/new', to: 'passwords#new', as: :new_password
  post 'password/reset', to: 'passwords#create', as: :reset_password
  get 'password/edit', to: 'passwords#edit', as: :edit_password
  patch 'password/update', to: 'passwords#update', as: :password_update

  # Definição da rota raiz para a tela de login
  root 'users#login'

  # Rota para a tela inicial
  get 'home', to: 'users#home', as: 'home'

  # Rota para sair da conta
  get '/logout', to: 'sessions#destroy'

  # Rotas para emitir relatórios
  get 'emitir_relatorio', to: 'reports#emitir', as: 'emitir_relatorio'
 
  # Definições das rotas para os recursos
  resources :tarefas do
    member do
      patch :marcar_como_concluida
    end
  end
  resources :categorias
  resources :lembretes
  resources :metas do
    member do
      patch :marcar_como_concluida
    end
  end
  resources :users
  resources :planner_views
  resources :statuses

end

app/models/user.rb
class User < ApplicationRecord
  require 'bcrypt'

  attr_accessor :raw_password, :raw_password_confirmation

  before_validation :confirm_password

  validates :nome, presence: true, length: { minimum: 6, message: "O nome deve ter no mínimo 6 caracteres" }
  validates :senha, presence: true
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP, message: "Não é um email válido" }, uniqueness: { case_sensitive: false, message: "já cadastrado" }

  # Autentica a senha usando BCrypt
  def authenticate(raw_password)
    BCrypt::Password.new(senha) == raw_password
  end

  before_save :downcase_email

  # Gera um token de redefinição de senha e define o tempo de expiração
  def generate_reset_password_token
    self.reset_password_token = SecureRandom.urlsafe_base64.to_s
    self.reset_password_token_expires_at = 2.hours.from_now
    save(validate: false) # Evita validações para que o token possa ser salvo
    UserMailer.reset_password_email(self).deliver_now
  end

  # Verifica se o token de redefinição ainda é válido
  def reset_password_token_valid?
    reset_password_token_expires_at && reset_password_token_expires_at > Time.current
  end

  # Invalida o token após o uso, garantindo que ele não possa ser reutilizado
  def invalidate_reset_password_token
    self.reset_password_token = nil
    self.reset_password_token_expires_at = nil
    save(validate: false) # Salva as mudanças sem validações
  end

  private

  # Transforma o e-mail em letras minúsculas antes de salvar
  def downcase_email
    self.email = email.downcase if email.present?
  end

  # Confirmação da senha antes de salvar
  def confirm_password
    if raw_password.present? && raw_password_confirmation.present? && raw_password == raw_password_confirmation
      self.senha = BCrypt::Password.create(raw_password)
    elsif raw_password.present?
      errors.add(:base, "As senhas não coincidem")
      throw(:abort)
    else
      errors.add(:base, "É preciso cadastrar uma senha")
      throw(:abort)
    end
  end
end

app/controllers/user_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: %i[show edit update destroy]
  
    # GET /users
    # GET /users.json
    def index
      @users = User.all
    end
  
    # GET /users/1
    # GET /users/1.json
    def show
    end
  
    # GET /users/new
    def new
      @user = User.new
    end
  
    # GET /users/1/edit
    def edit
    end
  
    # POST /users
    # POST /users.json
    def create
      @user = User.new(user_params)
  
      respond_to do |format|
        if @user.save
          format.html { redirect_to @user, notice: 'User was successfully created.' }
          format.json { render :show, status: :created, location: @user }
        else
          format.html { render :new }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # PATCH/PUT /users/1
    # PATCH/PUT /users/1.json
    def update
      respond_to do |format|
        if @user.update(user_params)
          format.html { redirect_to @user, notice: 'User was successfully updated.' }
          format.json { render :show, status: :ok, location: @user }
        else
          format.html { render :edit }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /users/1
    # DELETE /users/1.json
    def destroy
      @user.destroy
      respond_to do |format|
        format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  
    private
      # Use callbacks to share common setup or constraints between actions.
      def set_user
        @user = User.find(params[:id])
      end
  
      # Only allow a list of trusted parameters through.
      def user_params
        params.require(:user).permit(:name, :email, :senha, :planner_view_id)
      end
  end
  

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: %i[show edit update destroy]
  
    # GET /users
    # GET /users.json
    def index
      @users = User.all
    end

    #GET ALL USERS
    def get_all_users
      @users = User.all
    end
  
    # GET /users/1
    # GET /users/1.json
    def show
    end
  
    # GET /users/new
    def new
      @user = User.new
    end
  
    # GET /users/1/edit
    def edit
    end
  
    def login
    end

    def home
    end

    # POST /users
    # POST /users.json
    def create
      @user = User.new(user_params)

      if @user.save
        flash[:sucess] = "Usuário cadastrado com sucesso."
        redirect_to home_path  
      else
        flash[:error] = @user.errors.full_messages.to_sentence
        render :new
      end
    end
  
    # PATCH/PUT /users/1
    # PATCH/PUT /users/1.json
    def update
      respond_to do |format|
        if @user.update(user_params)
          format.html { redirect_to @user, notice: 'User was successfully updated.' }
          format.json { render :show, status: :ok, location: @user }
        else
          format.html { render :edit }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /users/1
    # DELETE /users/1.json
    def destroy
      @user.destroy
      respond_to do |format|
        format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    def create_session
      # Aqui você pode lidar com a autenticação do usuário
      user = User.find_by(email: params[:email])
  
      if user && user.authenticate(params[:password])
        session[:user_id] = user.id
        flash[:success] = "Login bem-sucedido!"
        redirect_to home_path  
      else
        flash[:error] = "Email ou senha inválidos."
        render :login
      end
    end
  
    private
      # Use callbacks to share common setup or constraints between actions.
      def set_user
        @user = User.find(params[:id])
      end
  
      # Only allow a list of trusted parameters through.
      def user_params
        params.require(:user).permit(:nome, :email, :raw_password, :raw_password_confirmation)
      end

  end
  

app/helpers/users_helper.rb
module UsersHelper

  def input_with_icon(form, field_name, icon_path, placeholder)
    # Lê o conteúdo do SVG
    icon_url = image_url icon_path

    input_field = form.text_field(field_name, class: 'form-control custom-input', placeholder: placeholder,
                                  style: "background-image: url('#{icon_url}')")

    "<div class='form-group'>#{input_field}</div>".html_safe
  end



  def password_input_with_icon(form, field_name, icon_path, placeholder)
    icon_url = image_url icon_path

    input_field = form.password_field(field_name, class: 'form-control custom-input', placeholder: placeholder,
                                      style: "background-image: url('#{icon_url}')")

    "<div class='form-group'>#{input_field}</div>".html_safe
  end

end

app/views/users/get_all_users.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lista de Usuários</title>
</head>
<body>
<h1>Lista de Usuários</h1>

<% if @users.any? %>
  <table>
    <thead>
    <tr>
      <th>Nome</th>
      <th>Email</th>
    </tr>
    </thead>
    <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.nome %></td>
        <td><%= user.email %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  <p>Nenhum usuário encontrado.</p>
<% end %>

</body>
</html>

app/views/users/home.html.erb
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <title>PLPlanner</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;700&display=swap" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
</head>
<body>
    <%= render 'layouts/header' %>
    <%= render 'calendario/calendar' %>
</body>
</html>

app/views/users/login.html.erb
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <title>PlpPlannerView</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>

    <%= javascript_importmap_tags %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_include_tag 'application' %>

    <%= stylesheet_link_tag "login", "data-turbo-track": "reload" %> <!-- Link para o CSS específico -->
</head>
<body id="login-page"> <!-- ID específico para login -->
  <div class="signup-container">
    <div class="signup-form">
      <h2>FAÇA LOGIN</h2>
      <%= form_with(url: create_session_users_path, local: true) do |form| %>
        <%= input_with_icon(form, :email, 'Email.svg', 'Email') %>
        <%= password_input_with_icon(form, :password, 'Password.svg', 'Senha') %>

        <p><%= link_to "Esqueceu sua senha?", new_password_path %></p>

        <p><%= link_to "Não tem uma conta? Cadastre-se", new_user_path %></p>

        <div class="form-group">
          <%= form.submit "ENTRAR", class: "btn-primary"%>
        </div>
      <% end %>
    </div>

    <div class="signup-image">
      <%= image_tag 'NewUser.png', alt: 'Bem-vindo de volta!' %>
    </div>
  </div>

  <% if flash[:success] %>
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            toastr.success('<%= j flash[:success] %>');
        });
    </script>
  <% elsif flash[:error] %>
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            toastr.error('<%= j flash[:error] %>');
        });
    </script>
  <% end %>
</body>
</html>

app/views/users/new.html.erb
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <title>PlpPlannerView</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>

    <%= javascript_importmap_tags %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_include_tag 'application' %>

    <%= stylesheet_link_tag "users", "data-turbo-track": "reload" %>
  </head>
  <body>
    <div class="signup-container">
      <div class="signup-image">
        <%= image_tag 'NewUser.png', alt: 'Organize o seu dia a dia' %>
      </div>

      <div class="signup-form">
        <h2>CRIE UMA<br/>CONTA</h2>
        <%= form_with(model: @user) do |form| %>

          <%= input_with_icon(form, :nome, 'User.svg', 'Nome Completo') %>

          <%= input_with_icon(form, :email, 'Email.svg', 'Email') %>

          <%= password_input_with_icon(form, :raw_password, 'Password.svg', 'Senha') %>

          <%= password_input_with_icon(form, :raw_password_confirmation, 'Password.svg', 'Confirme sua Senha') %>

          <p><%= link_to "Já tenho cadastro", root_path %></p>

          <div class="form-group">
            <%= form.submit "CADASTRAR", class: "btn-primary"%>
          </div>
        <% end %>


      </div>
    </div>

    <% if flash[:success] %>
      <script>
          document.addEventListener('DOMContentLoaded', function() {
              toastr.success('<%= j flash[:success] %>');
          });
      </script>
    <% elsif flash[:error] %>
      <script>
          document.addEventListener('DOMContentLoaded', function() {
              toastr.error('<%= j flash[:error] %>');
          });
      </script>
    <% end %>


  </body>
</html>