config/routes.rb
Rails.application.routes.draw do
  get 'passwords/new'
  get 'passwords/edit'
  
  # Rota para verificar a saúde da aplicação
  get "up" => "rails/health#show", as: :rails_health_check

  # Rotas de login e cadastro
  get 'signup', to: 'users#new', as: 'signup'
  post 'signup', to: 'users#create'

  get 'get_all_users', to: 'users#get_all_users'
  get 'login', to: 'users#login'
  post 'login', to: 'users#create_session', as: 'create_session_users'

  # Rota para redefinir senha
  get 'password/new', to: 'passwords#new', as: :new_password
  post 'password/reset', to: 'passwords#create', as: :reset_password
  get 'password/edit', to: 'passwords#edit', as: :edit_password
  patch 'password/update', to: 'passwords#update', as: :password_update

  # Definição da rota raiz para a tela de login
  root 'users#login'

  # Rota para a tela inicial
  get 'home', to: 'users#home', as: 'home'

  # Rota para sair da conta
  get '/logout', to: 'sessions#destroy'

  # Rotas para emitir relatórios
  get 'emitir_relatorio', to: 'reports#emitir', as: 'emitir_relatorio'
 
  # Definições das rotas para os recursos
  resources :tarefas do
    member do
      patch :marcar_como_concluida
    end
  end
  resources :categorias
  resources :lembretes
  resources :metas do
    member do
      patch :marcar_como_concluida
    end
  end
  resources :users
  resources :planner_views
  resources :statuses

end

app/views/layouts/_header.html.erb
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <title>PLPlanner</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'header', media: 'all' %>
    <link href="https://fonts.googleapis.com/css2?family=Rancho&display=swap" rel="stylesheet">
    <style>
        .user-icon {
            position: relative;
            display: inline-block;
        }

        .dropdown-content {
            display: none;
            position: absolute;
            background-color: #f9f9f9;
            min-width: 160px;
            box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
            z-index: 1;
        }

        .dropdown-content a {
            color: black;
            padding: 12px 16px;
            text-decoration: none;
            display: block;
        }

        .dropdown-content a:hover {
            background-color: #f1f1f1;
        }

        .user-icon:hover .dropdown-content {
            display: block;
        }
    </style>
</head>
<body>
    <header class="main-header">
        <div class="logo">
            <h1>PLPlanner</h1>
        </div>
        <div class="search-bar">
            <input type="text" placeholder="Buscar por atividades">
        </div>
        <div class="user-icon">
            <%= image_tag 'user-icon.svg', alt: 'usuário' %>
            <div class="dropdown-content">
            <%= link_to 'Logout', logout_path, method: :delete %>
            </div>
        </div>
    </header>
    <%= yield %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PlpPlannerView</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Estilos -->
    <%= stylesheet_link_tag "application", "data-turbolinks-track": "reload" %>
    <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/toastify-js@1.12.0/src/toastify.min.css", "data-turbolinks-track": "reload" %>

    <!-- Scripts -->
    <%= javascript_importmap_tags %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>